---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/8/8 15:46

require "lib/class"

---@class UnitManager : table
UnitManager = class(nil, 'UnitManager');

function UnitManager:ctor()

end

function UnitManager:Update()

end

function UnitManager:Close()

end

return UnitManager;