---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022-08-22 22:57:30
---
--- 通过Java工具类自动生成，请勿修改，重新生成会被覆盖
---

require "Lib/class"

---@class ServerLogTool : table
ServerLogTool = class(nil, 'ServerLogTool');

function ServerLogTool:ctor()
end

-- 打印log
---@param logLevel number log级别
---@param msg string log消息
---@type function
---@return void
---@public
function ServerLogTool:log(logLevel, msg)
    return
end

-- 获取堆栈
---@param log string 
---@type function
---@return string
---@public
function ServerLogTool:traceback(log)
    return
end

-- log级别是否可用
---@param logLevel number log级别
---@type function
---@return boolean
---@public
function ServerLogTool:isLogEnabled(logLevel)
    return
end

return ServerLogTool;
