---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022-08-22 22:57:30
---
--- 通过Java工具类自动生成，请勿修改，重新生成会被覆盖
---
--- 服务端Java调用库

require "Lib/class"

---@class ServerLib : table
---@field battle ServerLuaBattle
---@field logTool ServerLogTool
ServerLib = class(nil, 'ServerLib');

function ServerLib:ctor()
    self.battle = luajava.bindClass("com.hjc.demo.convert.lib.LuaBattleFunction")
    self.logTool = luajava.bindClass("com.hjc.lua.log.LuaLogTool")
end



