---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2021/12/4 12:05
--- 消息接收器

COMMAND = {};

--外部调用收到msg table(服务器用)
---@param fightCoreLua FightCoreLua 战斗
---@param uid number 发送协议的玩家id，如果是战斗房间消息该值为nil
---@param id number 协议id
---@param table table 协议
function COMMAND.ReceiveMsgTable(fightCoreLua, uid, id, table)
    if fightCoreLua == nil then
        print("ReceiveMsgBytes id[" .. tostring(id) .. "] fightCoreLua nil !!!")
        return
    end
    fightCoreLua:ReceiveMsg(uid, id, table)
end

--向客户端广播消息 服务器端逻辑核心调用
---@param battleId number 广播的战斗id
---@param id number 协议id
---@param table table 协议
---@param includeServer boolean 是否广播给服务器逻辑核
function COMMAND.BroadcastCommandToClientTable(battleId, id, table, includeServer)
    ---@type boolean
    local _includeServer = false
    if includeServer then
        _includeServer = includeServer
    end

    -- 服务端调用服务端库发送
    SERVER_LIB.battle:invokeBroadcastMessageByLua(battleId, id, table, _includeServer);
end

