---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/8/8 15:33

require "lib/class"
require "logic/UnitManager"

---@class BattleRoom : table
BattleRoom = class(nil, 'BattleRoom');

function BattleRoom:ctor(_battleId)
    self.battleId = _battleId
    self.a = 0
    --print("ctor:" .. tostring(self.battleId))
end

function BattleRoom:Init()
    self.unitManager = UnitManager.New()
    --print("Init:" .. tostring(self.battleId))
end

function BattleRoom:Run()
    --print("Run:" .. tostring(self.battleId))
    --if self.unitManager then
    --    self.unitManager:Update()
    --end
    self.a = self.a + 1
    --print(a)
end

function BattleRoom:Close()
    if self.unitManager then
        self.unitManager:Close()
    end

    print(tostring(self.battleId) .. " : " .. tostring(self.a))
end

return BattleRoom;