---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022-08-22 22:39:28
---
--- 技能退出节点

require "Lib/class"

---@class SkillNodeExitData : table
---@field type number
---@field param string
---@field nextNodeID number[]
SkillNodeExitData = class(nil, 'SkillNodeExitData');

function SkillNodeExitData:ctor(_type, _param, _nextNodeID)
    self.type = _type
    self.param = _param
    self.nextNodeID = _nextNodeID
end

return SkillNodeExitData;
