---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022-08-22 22:39:28
---
--- 技能节点参数

require "Lib/class"

---@class SkillNodeParam : table
---@field time string
---@field barrageID string
---@field spreadParam string
---@field elementID string
---@field shootEffect string
---@field consume string
---@field colliderId string
---@field addBuff string[]
---@field removeBuff string[]
---@field maxSpeedRatio number
---@field currentSpeedRatio number
---@field loopId number
---@field loopTime number
---@field loopDelayTime number
---@field isForceBreak boolean
---@field buffGroupIds string[]
---@field selfAll boolean
SkillNodeParam = class(nil, 'SkillNodeParam');

function SkillNodeParam:ctor(_time, _barrageID, _spreadParam, _elementID, _shootEffect, _consume, _colliderId, _addBuff, _removeBuff, _maxSpeedRatio, _currentSpeedRatio, _loopId, _loopTime, _loopDelayTime, _isForceBreak, _buffGroupIds, _selfAll)
    self.time = _time
    self.barrageID = _barrageID
    self.spreadParam = _spreadParam
    self.elementID = _elementID
    self.shootEffect = _shootEffect
    self.consume = _consume
    self.colliderId = _colliderId
    self.addBuff = _addBuff
    self.removeBuff = _removeBuff
    self.maxSpeedRatio = _maxSpeedRatio
    self.currentSpeedRatio = _currentSpeedRatio
    self.loopId = _loopId
    self.loopTime = _loopTime
    self.loopDelayTime = _loopDelayTime
    self.isForceBreak = _isForceBreak
    self.buffGroupIds = _buffGroupIds
    self.selfAll = _selfAll
end

return SkillNodeParam;
