---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022-08-22 22:39:28
---
--- 掉落表数据

require "Lib/class"

---@class FallDictData : table
---@field index number index
---@field conditionType number 掉落条件
---@field conditionParam number 掉落条件参数
---@field activeTime number 生效次数
---@field fallObjectId number 掉落id
---@field fallCount number 掉落数量
---@field cdLimitTime number 冷却时间
---@field adaptElement boolean 适应元素
FallDictData = class(nil, 'FallDictData');

function FallDictData:ctor(_index, _conditionType, _conditionParam, _activeTime, _fallObjectId, _fallCount, _cdLimitTime, _adaptElement)
    self.index = _index
    self.conditionType = _conditionType
    self.conditionParam = _conditionParam
    self.activeTime = _activeTime
    self.fallObjectId = _fallObjectId
    self.fallCount = _fallCount
    self.cdLimitTime = _cdLimitTime
    self.adaptElement = _adaptElement
end

return FallDictData;
