---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/8/17 22:49
---
-- 外层赋值确定客户端启动logic_core
---@return boolean 客户端启动logic core
function IsClient()
    return isClient
end

-- 外层赋值确定服务器启动logic core
---@return boolean 服务器启动logic core
function IsServer()
    return isServer
end

require "class"
require "FightCoreLua"

if IsServer() then
    -- 执行服务器初始化逻辑
    -- 服务端Java调用库
    require "Lib/Server/ServerLib"
    require 'org.luaj.vm2.lib.DebugLib'

    -- 服务端Java调用库
    ---@type ServerLib
    SERVER_LIB = ServerLib.New()
end

--外层调用启动logic_core
function Main()
    Init()
end

function Init()
    -- 初始化全局的内容
    print("FightManager Init")
end

--- 创建战斗核心
---@return FightCoreLua 战斗核心
function CreateFightCore(_battleId)
    ---@type FightCoreLua
    local fightCoreLua = FightCoreLua.New(_battleId)

    if IsClient() then
        -- 客户端可以使用全局战斗核心
        ---@type FightCoreLua
        CLIENT_FIGHT_CORE = fightCoreLua
        -- 客户端创建完可以直接初始化
        fightCoreLua:Init()
    end

    return fightCoreLua
end

--- 初始化战斗核心（服务端把这一步拆开做，需要等创建完扔进Raid对象管理，再做初始化）
---@param _fightCoreLua FightCoreLua
function InitFightCore(_fightCoreLua)
    if _fightCoreLua == nil then
        return
    end
    -- 初始化
    _fightCoreLua:Init()
end

-- 初始化战斗房间
---@param battleData table 战斗初始化相关数据
function InitBattleData(fightCoreLua, battleData)
    if not fightCoreLua or not battleData or not battleData.battleId then
        return
    end
    -- battleData是战场完整数据，结构是msg.BattleEnterInfo
    fightCoreLua:InitBattleData(battleData)
end

---@type function
---@param _fightCoreLua FightCoreLua
function Close(_fightCoreLua)
    if _fightCoreLua then
        _fightCoreLua:Close()
    end
end

--- 获取战斗核心
---@param _battleId number
function GetFightCore(_battleId)
    if IsClient() then
        -- 客户端使用全局唯一战斗核心
        return CLIENT_FIGHT_CORE
    else
        -- 服务端从Java内存获取战斗核心
        return SERVER_LIB.battle:getFightCoreLua(_battleId)
    end
end

--- 获取战斗房间
---@param _battleId number
---@return BattleRoom
function GetBattleRoom(_battleId)
    local fightCoreLua = GetFightCore(_battleId)
    if not fightCoreLua then
        return
    end
    return fightCoreLua.battleRoom
end

